[telegram]
token = "1313654865:AAEPfEsuDxb4iC3rSK1q7czP6NdKyix09LU"
workers = 1
admins = [677799710]
admins_only = false
maintenance_mode = false
persistent_temp_data = true

[pyrogram]
enabled = false
api_id = 1477063
api_hash = "8f2df757733810640649725e7fe53eb1"

[sqlite]
filename = "stickersbot.sqlite"

[bot]
sourcecode = ""
issues = ""
channel = ""
